const GET_WORK = 'GET_WORK'
const GET_WORK_SUCCESS = 'GET_WORK_SUCCESS'
const GET_WORK_ID = 'GET_WORK_ID'
const GET_WORK_ID_SUCCESS = 'GET_WORK_ID_SUCCESS'
const SET_PLACE = 'SET_PLACE'


export {
    GET_WORK,
    GET_WORK_SUCCESS,
    GET_WORK_ID,
    GET_WORK_ID_SUCCESS,
    SET_PLACE,
}